version: '3.8'

services:
  # Backend API
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://tradepulse:tradepulse@db:5432/tradepulse
      - SECRET_KEY=your-super-secret-key-change-in-production
      - DEBUG=false
      - ALPHA_VANTAGE_API_KEY=IIKESCGRVVVG7T3B
    depends_on:
      - db
    restart: unless-stopped

  # Frontend Web App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped

  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=tradepulse
      - POSTGRES_PASSWORD=tradepulse
      - POSTGRES_DB=tradepulse
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
